# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 25, 110, 50))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 25, 110, 50))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 25, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.accText1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText1.setGeometry(QtCore.QRect(60, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText1.setFont(font)
        self.accText1.setAutoFillBackground(False)
        self.accText1.setObjectName("accText1")
        self.accText2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText2.setGeometry(QtCore.QRect(60, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText2.setFont(font)
        self.accText2.setObjectName("accText2")
        self.accText3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText3.setGeometry(QtCore.QRect(60, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText3.setFont(font)
        self.accText3.setObjectName("accText3")
        self.accText4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText4.setGeometry(QtCore.QRect(60, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText4.setFont(font)
        self.accText4.setObjectName("accText4")
        self.accText5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText5.setGeometry(QtCore.QRect(60, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText5.setFont(font)
        self.accText5.setObjectName("accText5")
        self.accText6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText6.setGeometry(QtCore.QRect(60, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText6.setFont(font)
        self.accText6.setObjectName("accText6")
        self.accText7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText7.setGeometry(QtCore.QRect(60, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText7.setFont(font)
        self.accText7.setObjectName("accText7")
        self.accText8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText8.setGeometry(QtCore.QRect(60, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText8.setFont(font)
        self.accText8.setObjectName("accText8")
        self.accText9 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText9.setGeometry(QtCore.QRect(60, 390, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText9.setFont(font)
        self.accText9.setObjectName("accText9")
        self.accText10 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.accText10.setGeometry(QtCore.QRect(60, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.accText10.setFont(font)
        self.accText10.setObjectName("accText10")
        self.passText2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText2.setGeometry(QtCore.QRect(250, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText2.setFont(font)
        self.passText2.setObjectName("passText2")
        self.passText8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText8.setGeometry(QtCore.QRect(250, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText8.setFont(font)
        self.passText8.setObjectName("passText8")
        self.passText4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText4.setGeometry(QtCore.QRect(250, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText4.setFont(font)
        self.passText4.setObjectName("passText4")
        self.passText5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText5.setGeometry(QtCore.QRect(250, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText5.setFont(font)
        self.passText5.setObjectName("passText5")
        self.passText6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText6.setGeometry(QtCore.QRect(250, 270, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText6.setFont(font)
        self.passText6.setObjectName("passText6")
        self.passText9 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText9.setGeometry(QtCore.QRect(250, 390, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText9.setFont(font)
        self.passText9.setObjectName("passText9")
        self.passText10 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText10.setGeometry(QtCore.QRect(250, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText10.setFont(font)
        self.passText10.setObjectName("passText10")
        self.passText1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText1.setGeometry(QtCore.QRect(250, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText1.setFont(font)
        self.passText1.setAutoFillBackground(False)
        self.passText1.setObjectName("passText1")
        self.passText7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText7.setGeometry(QtCore.QRect(250, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText7.setFont(font)
        self.passText7.setObjectName("passText7")
        self.passText3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.passText3.setGeometry(QtCore.QRect(250, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.passText3.setFont(font)
        self.passText3.setObjectName("passText3")
        self.statLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel1.setGeometry(QtCore.QRect(390, 65, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel1.setFont(font)
        self.statLabel1.setObjectName("statLabel1")
        self.statLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel3.setGeometry(QtCore.QRect(390, 145, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel3.setFont(font)
        self.statLabel3.setObjectName("statLabel3")
        self.statLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel2.setGeometry(QtCore.QRect(390, 105, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel2.setFont(font)
        self.statLabel2.setObjectName("statLabel2")
        self.statLabel5 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel5.setGeometry(QtCore.QRect(390, 225, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel5.setFont(font)
        self.statLabel5.setObjectName("statLabel5")
        self.statLabel4 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel4.setGeometry(QtCore.QRect(390, 185, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel4.setFont(font)
        self.statLabel4.setObjectName("statLabel4")
        self.statLabel7 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel7.setGeometry(QtCore.QRect(390, 305, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel7.setFont(font)
        self.statLabel7.setObjectName("statLabel7")
        self.statLabel6 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel6.setGeometry(QtCore.QRect(390, 265, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel6.setFont(font)
        self.statLabel6.setObjectName("statLabel6")
        self.statLabel8 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel8.setGeometry(QtCore.QRect(390, 345, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel8.setFont(font)
        self.statLabel8.setObjectName("statLabel8")
        self.statLabel10 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel10.setGeometry(QtCore.QRect(390, 425, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel10.setFont(font)
        self.statLabel10.setObjectName("statLabel10")
        self.statLabel9 = QtWidgets.QLabel(self.centralwidget)
        self.statLabel9.setGeometry(QtCore.QRect(390, 385, 110, 50))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(20)
        self.statLabel9.setFont(font)
        self.statLabel9.setObjectName("statLabel9")
        self.runLogin = QtWidgets.QPushButton(self.centralwidget)
        self.runLogin.setGeometry(QtCore.QRect(60, 480, 101, 41))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.runLogin.setFont(font)
        self.runLogin.setObjectName("runLogin")
        
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(250, 550, 101, 41))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.exportButton.setFont(font)
        self.exportButton.setObjectName("exportButton")

        self.loadFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFileButton.setGeometry(QtCore.QRect(60, 550, 101, 41))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.loadFileButton.setFont(font)
        self.loadFileButton.setObjectName("loadFileButton")
        
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(250, 480, 101, 41))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ptt洗登入次數器"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">帳號</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">密碼</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">狀態</span></p></body></html>"))
        self.statLabel1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.statLabel9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">N/A</span></p></body></html>"))
        self.runLogin.setText(_translate("MainWindow", "自動登入/登出"))
        self.clear.setText(_translate("MainWindow", "全部清除"))
        self.exportButton.setText(_translate("MainWindow", "匯出帳號密碼"))
        self.loadFileButton.setText(_translate("MainWindow", "讀取帳密檔"))

