from enum import Enum

class Status(Enum):
    STAT_CONNECTING = 'STAT_CONNECTING'
    STAT_LOGIN_SUCCESS = 'STAT_LOGIN_SUCCESS'
    STAT_LOGIN_FAILED = 'STAT_LOGIN_FAILED'
    STAT_SERVER_OVERLOAD = 'STAT_SERVER_OVERLOAD'
    STAT_OS_ERROR = 'STAT_OS_ERROR'
    STAT_FILE_IO_ERROR = 'STAT_FILE_IO_ERROR'
    STAT_RUNLOGIN_BUTTON_CLICKED = 'STAT_RUNLOGIN_BUTTON_CLICKED'
    STAT_CLEAR_BUTTON_CLICKED = 'STAT_CLEAR_BUTTON_CLICKED'
    STAT_EXPORT_BUTTON_CLICKED = 'STAT_EXPORT_BUTTON_CLICKED'
    STAT_LOADFILE_BUTTON_CLICKED = 'STAT_LOADFILE_BUTTON_CLICKED'
    STAT_LOADFILE_SUCCESS = 'STAT_LOADFILE_SUCCESS'
    STAT_EXPORT_SUCCESS = 'STAT_EXPORT_SUCCESS'
    STAT_WORK_DONE = 'STAT_WORK_DONE'